### ISSUE TITLE
getGeo.events and artist.getEvents not working, but maybe because LastFM API changed or broken?

### ISSUE THREAD

**Issue by lacostenycoder** [youpy/ruby-lastfm#81]
### Examples

```
lastfm = Lastfm.new(ENV['LAST_FM_KEY'],ENV['LAST_FM_SECRET'])

lastfm.geo.get_events(location: "New York")
>Lastfm::ApiError: Invalid Method - No method with that name in this package

lastfm.artist.get_events(artist: "Morrissey")
>Lastfm::ApiError: Invalid Method - No method with that name in this package
```
#### Relevant links as to API status

https://plus.google.com/+TimothyMalseed/posts/Sn6qcQuPDrX

Their status doesn't reflect deletion or changes in these methods.
http://status.last.fm/

Anyone else having these problems?  Or know what the issue is?  I reached out to LastFM but haven't heard back yet.

**Comment by youpy** [comment]
http://www.last.fm/api

`Geo.getEvents` and `Artist.getEvents` seems deleted on Last.fm Web Services.
